MetadataBundle\Domain\Entity\BaseMetadata:
    exclusion_policy: none

    properties:
        order:
            type: integer

        alias:
            type: string

        url:
            type: string

