services:
    wolnosciowiec.wiki.fetchers.git:
        class: WikiBundle\Service\Fetcher\GitFetcher
        arguments:
            storageManager: "@wolnosciowiec.wiki.manager.storage"
        tags:
            - { name: wolnosciowiec.wiki.fetchers }

    wolnosciowiec.wiki.fetchers.filesystem:
        class: WikiBundle\Service\Fetcher\FileSystemFetcher
        arguments:
            filesystem: "@wolnosciowiec.wiki.manager.filesystem"
            storageManager: "@wolnosciowiec.wiki.manager.storage"
        tags:
            - { name: wolnosciowiec.wiki.fetchers }

