imports:
    - { resource: fetchers.yml }
    - { resource: payload_factories.yml }
    - { resource: processors.yml }

services:
    wolnosciowiec.wiki.browser:
        class: WikiBundle\Service\Browser\DynamicPagesBrowser
        arguments:
            processor:  "@wolnosciowiec.wiki.processor"
            provider:   "@wolnosciowiec.wiki.provider.repository"
            storage:    "@wolnosciowiec.wiki.manager.storage"
            router:     "@wolnosciowiec.wiki.services.router"
            filesystem: "@wolnosciowiec.wiki.manager.filesystem"

    wolnosciowiec.wiki.fetcher:
        class: WikiBundle\Service\Fetcher\FetcherService
        arguments:
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            logger:         "@logger"

    wolnosciowiec.wiki.factory.payload:
        class: WikiBundle\Factory\Payload\PayloadFactory

    wolnosciowiec.wiki.manager.filesystem:
        class: WikiBundle\Service\StorageManager\FileSystemOperator

    wolnosciowiec.wiki.manager.storage:
        class: WikiBundle\Service\StorageManager\StorageManager
        arguments:
            storagePath: '%kernel.root_dir%/Storage'
            compiledFilesPath: '%kernel.root_dir%/Compiled'
            filesystem: "@wolnosciowiec.wiki.manager.filesystem"

    wolnosciowiec.wiki.provider.repository:
        class: WikiBundle\Service\RepositoryProvider\RepositoryProvider
        arguments:
            serializer: "@serializer"

    wolnosciowiec.wiki.handler.payload:
        class: WikiBundle\Service\PayloadHandler\PayloadHandlerService
        arguments:
            fetcherService: "@wolnosciowiec.wiki.fetcher"
            payloadFactory: "@wolnosciowiec.wiki.factory.payload"
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            fileProcessor:  "@wolnosciowiec.wiki.processor"
            logger:         "@logger"

    wolnosciowiec.wiki.expression:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

    wolnosciowiec.wiki.services.router:
        class: WikiBundle\Service\Routing\Router
        arguments:
            cache: "@repository_cache"
            filesystem: "@wolnosciowiec.wiki.manager.filesystem"
            repositories: "@wolnosciowiec.wiki.provider.repository"
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            logger: "@logger"
            eventDispatcher: "@event_dispatcher"

