imports:
    - { resource: fetchers.yml }
    - { resource: payload_factories.yml }
    - { resource: processors.yml }
    - { resource: extensions.yml }

services:
    wolnosciowiec.wiki.browser:
        class: WikiBundle\Service\Browser\StaticPagesBrowser
        arguments:
            groupsDirectory: '%kernel.root_dir%/Compiled'

    wolnosciowiec.wiki.fetcher:
        class: WikiBundle\Service\Fetcher\FetcherService
        arguments:
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            logger:         "@logger"

    wolnosciowiec.wiki.factory.payload:
        class: WikiBundle\Factory\Payload\PayloadFactory

    wolnosciowiec.wiki.manager.filesystem:
        class: WikiBundle\Service\StorageManager\FileSystemOperator

    wolnosciowiec.wiki.manager.storage:
        class: WikiBundle\Service\StorageManager\StorageManager
        arguments:
            storagePath: '%kernel.root_dir%/Storage'
            compiledFilesPath: '%kernel.root_dir%/Compiled'
            filesystem: "@wolnosciowiec.wiki.manager.filesystem"

    wolnosciowiec.wiki.provider.repository:
        class: WikiBundle\Service\RepositoryProvider\RepositoryProvider
        arguments:
            serializer: "@serializer"

    wolnosciowiec.wiki.handler.payload:
        class: WikiBundle\Service\PayloadHandler\PayloadHandlerService
        arguments:
            fetcherService: "@wolnosciowiec.wiki.fetcher"
            payloadFactory: "@wolnosciowiec.wiki.factory.payload"
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            fileProcessor:  "@wolnosciowiec.wiki.processor"
            logger:         "@logger"

