services:
    #repository_cache:
    #    class: WikiBundle\Service\Cache\Redis
    #    arguments:
    #        predis: "@predis"

    repository_cache:
        class: WikiBundle\Service\Cache\VoidCache

    predis:
        class: Predis\Client
        arguments:
            options:
                scheme: '%redis_scheme%'
                host: '%redis_host%'
                port: '%redis_port%'
                path: '%redis_socket_path%'
