services:
    wolnosciowiec.wiki.extension.layout:
        class: LayoutBundle\Event\LayoutEventListener
        arguments:
            storageManager: "@wolnosciowiec.wiki.manager.storage"
            logger:         "@logger"
        tags:
            - { name: kernel.event_listener, event: "postCompileFile", priority: 100 }
